[default]
address = "0.0.0.0"
port = 8000
iface = "enp0s9"
keys_cleanup_interval_seconds = 60
translation_cleanup_interval_seconds = 5
cpu_threshold = 5.0
timestamp_threshold_seconds = 60  
force_cleanup_every = 20
default_padding_probability = 30
default_dummy_probability = 30
default_fragmentation_probability = 30

# Configurazione TLS
[default.tls]
certs = "/path/to/cert.pem"
key = "/path/to/key.pem"  
